name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      upload_artifact:
        description: 'Upload artifact'
        required: false
        default: false
        type: boolean
      artifact_name:
        description: 'Artifact name'
        required: false
        default: 'ois'
        type: string
  workflow_dispatch:
  push:
    branches:
      - master

env:
  node_version: 20

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache-dependency-path: package-lock.json

      # Cache .nx directory
      - uses: actions/cache@v3
        with:
          path: .nx/cache
          key: ${{ runner.os }}-node${{ env.node_version }}-${{ hashFiles('**/nx.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.node_version }}

      # Install dependencies
      - run: npm ci --legacy-peer-deps

      # Lint, test, and build
      - run: npx nx affected -t lint test build-chromium

      # Zip the build artifact
      - if: ${{ github.event.inputs.upload_artifact == true }}
        name: Create zip
        working-directory: dist/ois
        run: zip -r ../${{ github.event.inputs.artifact_name }}.zip .

      # Upload artifact
      - if: ${{ github.event.inputs.upload_artifact == true }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.artifact_name }}.zip
          path: dist/${{ github.event.inputs.artifact_name }}.zip
