name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  node_version: 20

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache-dependency-path: package-lock.json

      # Cache .nx directory
      - uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-node${{ env.node_version }}-${{ hashFiles('**/nx.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.node_version }}

      # Install dependencies
      - run: npm ci --legacy-peer-deps

      # Lint, test, and build
      - run: npx nx affected -t lint test build-chromium
