name: Publish

on:
  push:
    tags: '*'

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      upload_artifact: true
      artifact_name: "ois-${{ github.ref_name }}"

  publish:
    name: Publish OIS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: "ois-${{ github.ref_name }}.zip"
          path: /tmp

      - name: Upload
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: /tmp/ois-${{ github.ref_name }}.zip
          extension-id: ${{ vars.WEBSTORE_EXTENSION_ID }}
          client-id: ${{ secrets.WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.WEBSTORE_REFRESH_TOKEN }}
