name: Publish

on:
  push:
    tags: '*'

env:
  node_version: 20
  artifact_name: ois-${{ github.ref_name }}

jobs:
  publish:
    name: Publish OIS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache-dependency-path: package-lock.json

      # Cache .nx directory
      - uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-node${{ env.node_version }}-${{ hashFiles('**/nx.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.node_version }}

      # Install dependencies
      - run: npm ci --legacy-peer-deps

      # Lint, test, and build
      - run: npx nx run-many -t lint test build-chromium

      # Zip the build artifact
      - name: Create zip
        working-directory: dist/ois
        run: zip -r ../${{ env.artifact_name }}.zip .

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}.zip
          path: dist/${{ env.artifact_name }}.zip

      # Upload to Chrome Web Store
      - name: Upload
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: /tmp/${{ env.artifact_name }}.zip
          extension-id: ${{ vars.WEBSTORE_EXTENSION_ID }}
          client-id: ${{ secrets.WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.WEBSTORE_REFRESH_TOKEN }}
